version: '3'

services:
  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    ports:
      - "3434:80"
    depends_on:
      - backend
    networks:
      - frindle

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "3000:3000"
    networks:
      - frindle
    volumes:
      - ./backend/books:/root/books

networks:
    frindle: